# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d6f8c6ab01e6866a6643cd49a21700701069a7385b083cbb3828942f02a9e6b1c8dad8a8adc2a431dd51789e45c748a97443c782085ec3b6fa8d2ae37d9ca4db

test:
  secret_key_base: 87e62e2f576ddcd8a39b12184705236261ca30108e487d0af3ec85a557ac6e6f536791adf6026a5d555146f4d10b3d0d301068dc8c184e5d630eb22e38e2a29d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
